### ISSUE TITLE
cannot import name 'login'

### ISSUE THREAD

**Issue by zatin009** [maxg203/Django-Tutorials#14]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial/urls.py", line 12, in <module>
    url(r'^account/', include('accounts.urls', namespace='accounts')),
  File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/computer/saleor_Learn/Django-Tutorials/accounts/urls.py", line 3, in <module>
    from django.contrib.auth.views import (
ImportError: cannot import name 'login'

**Comment by RK1126** [comment]
I am also having the same issue, did you find it's a solution?

**Comment by Unbalanced-Tree** [comment]
> 
> 
> Traceback (most recent call last):
> File "manage.py", line 22, in
> execute_from_command_line(sys.argv)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/**init**.py", line 381, in execute_from_command_line
> utility.execute()
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/**init**.py", line 375, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
> self.execute(*args, **cmd_options)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
> self.check()
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
> include_deployment_checks=include_deployment_checks,
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
> return checks.run_checks(**kwargs)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
> new_errors = check(app_configs=app_configs)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
> return check_resolver(resolver)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
> return check_method()
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
> for pattern in self.url_patterns:
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in **get**
> res = instance.**dict**[self.name] = self.func(instance)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
> patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/utils/functional.py", line 37, in **get**
> res = instance.**dict**[self.name] = self.func(instance)
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
> return import_module(self.urlconf_name)
> File "/usr/lib/python3.6/importlib/**init**.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 994, in _gcd_import
> File "", line 971, in _find_and_load
> File "", line 955, in _find_and_load_unlocked
> File "", line 665, in _load_unlocked
> File "", line 678, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial/urls.py", line 12, in
> url(r'^account/', include('accounts.urls', namespace='accounts')),
> File "/home/computer/saleor_Learn/Django-Tutorials/tutorial-env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
> urlconf_module = import_module(urlconf_module)
> File "/usr/lib/python3.6/importlib/**init**.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 994, in _gcd_import
> File "", line 971, in _find_and_load
> File "", line 955, in _find_and_load_unlocked
> File "", line 665, in _load_unlocked
> File "", line 678, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/home/computer/saleor_Learn/Django-Tutorials/accounts/urls.py", line 3, in
> from django.contrib.auth.views import (
> ImportError: cannot import name 'login'

I am also having the same issue, did you find it's a solution?

**Comment by MiKueen** [comment]
It's deprecated in django 2.x , so shift to class based views and use LoginView instead
from django.contrib.auth.views import (
	LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
	PasswordResetConfirmView, PasswordResetCompleteView
	)
If you're using older version of django then just removing _.views_ should solve the problem as "login" is in **django.contrib.auth**
